server:
  port: 9090

spring:
  application:
    name: delivery-point-rating-gateway
  cloud:
    gateway:
      routes:
        - id: delivery-point-rating-data-service
          uri: http://localhost:8080/
          predicates:
            - Path=/api/delivery-point-rating/data-service/**
            - Method=GET,POST,PUT,DELETE