name: Main branch pull request workflow

on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag delivery-point-rating-gateway:latest
      - name: Save Docker image
        run: docker save --output delivery-point-rating-gateway-image.tar delivery-point-rating-gateway:latest
      - name: Upload Docker image
        uses: actions/upload-artifact@v3
        with:
          path: delivery-point-rating-gateway-image.tar
          retention-days: 30
